export const TextureKey = {
  Bg: 'bg',
  Boss: 'boss',
  BottleHp: 'bottle-hp',
  BottleSuper: 'bottle-super',
  Bullet: 'bullet',
  BulletReject: 'bullet-reject',
  Egg: 'egg',
  Exit: 'exit',
  Flier: 'flier',
  FlierCrash: 'flier-crash',
  Ground: 'ground',
  Hud: 'hud',
  IceSpike: 'ice-spike',
  PlatformH: 'platform-h',
  PlatformV: 'platform-v',
  Player: 'player',
  PreloadBar: 'preload-bar',
  Rain: 'rain',
  Runner: 'runner',
  Shooter: 'shooter',
  ShooterReject: 'shooter-reject',
  Snowflake: 'snowflake',
  Spike: 'spike',
  Transparent: 'transparent',
  Tween: 'tween',
} as const;

export type TextureKeyValue = (typeof TextureKey)[keyof typeof TextureKey];
